"""new

Revision ID: d7b83bb0948e
Revises: 
Create Date: 2023-01-20 12:36:24.546672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7b83bb0948e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('board', schema=None) as batch_op:
        batch_op.add_column(sa.Column('board_length', sa.String(length=200), nullable=True))
        batch_op.drop_column('length')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('board', schema=None) as batch_op:
        batch_op.add_column(sa.Column('length', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.drop_column('board_length')

    # ### end Alembic commands ###
